package cli

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"penda/framework/app"
	"penda/framework/blueprint"
	fwctx "penda/framework/context"
	"penda/framework/middleware"
	"penda/framework/observability"
)

const usage = `penda - micro-framework CLI

Usage:
  penda new <name>      Create a new project scaffold
  penda run [addr]      Run built-in demo app (default :8080)
  penda routes          Print routes from built-in demo app
  penda doctor          Print environment diagnostics
`

// Run executes the CLI command.
func Run(args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		_, _ = io.WriteString(stdout, usage)
		return 0
	}

	switch args[0] {
	case "new":
		if len(args) < 2 || strings.TrimSpace(args[1]) == "" {
			_, _ = io.WriteString(stderr, "usage: penda new <name>\n")
			return 2
		}
		if err := cmdNew(args[1], stdout); err != nil {
			_, _ = io.WriteString(stderr, "error: "+err.Error()+"\n")
			return 1
		}
		return 0
	case "run":
		addr := ""
		if len(args) > 1 {
			addr = args[1]
		}
		server := buildDemoApp()
		if err := server.Run(addr); err != nil {
			_, _ = io.WriteString(stderr, "error: "+err.Error()+"\n")
			return 1
		}
		return 0
	case "routes":
		server := buildDemoApp()
		for _, route := range server.Routes() {
			_, _ = fmt.Fprintf(stdout, "%s %s\n", route.Method, route.Path)
		}
		return 0
	case "doctor":
		if err := cmdDoctor(stdout); err != nil {
			_, _ = io.WriteString(stderr, "error: "+err.Error()+"\n")
			return 1
		}
		return 0
	case "help", "--help", "-h":
		_, _ = io.WriteString(stdout, usage)
		return 0
	default:
		_, _ = io.WriteString(stderr, "unknown command: "+args[0]+"\n")
		_, _ = io.WriteString(stderr, usage)
		return 2
	}
}

func buildDemoApp() *app.App {
	server := app.New()
	metrics := observability.NewMetrics()

	server.Use(
		middleware.Recovery(),
		middleware.RequestID(),
		middleware.Logger(nil),
		middleware.CORS(middleware.CORSConfig{}),
		middleware.SecurityHeaders(middleware.SecurityHeadersConfig{}),
		metrics.Middleware(),
	)
	server.SetMaxBodyBytes(2 << 20)

	server.Register(blueprint.HealthBlueprint("/api"))
	server.Get("/health", observability.HealthHandler())
	server.Get("/ready", observability.ReadinessHandler(nil))
	server.Get("/metrics", metrics.Handler())

	api := server.Group("/api")
	api.Post("/echo", func(c *fwctx.Context) error {
		var payload map[string]any
		if err := c.BindJSON(&payload); err != nil {
			return err
		}
		return c.JSON(http.StatusOK, payload)
	})

	server.Get("/", func(c *fwctx.Context) error {
		return c.JSON(http.StatusOK, map[string]string{
			"message": "penda demo app is running",
		})
	})

	return server
}

func cmdDoctor(stdout io.Writer) error {
	wd, err := os.Getwd()
	if err != nil {
		return err
	}

	_, _ = fmt.Fprintf(stdout, "Go: %s\n", runtime.Version())
	_, _ = fmt.Fprintf(stdout, "OS/Arch: %s/%s\n", runtime.GOOS, runtime.GOARCH)
	_, _ = fmt.Fprintf(stdout, "Working directory: %s\n", wd)
	return nil
}

func cmdNew(name string, stdout io.Writer) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return errors.New("project name cannot be empty")
	}

	absPath, err := filepath.Abs(name)
	if err != nil {
		return err
	}

	if _, err := os.Stat(absPath); err == nil {
		return fmt.Errorf("directory already exists: %s", absPath)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}

	if err := os.MkdirAll(absPath, 0o755); err != nil {
		return err
	}

	mainFile := `package main

import (
    "net/http"

    "penda/framework/app"
    fwctx "penda/framework/context"
)

func main() {
    server := app.New()

    server.Get("/health", func(c *fwctx.Context) error {
        return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
    })

    if err := server.Run(":8080"); err != nil {
        panic(err)
    }
}
`
	goModFile := "module " + name + "\n\ngo 1.22.0\n"
	readmeFile := "# " + name + "\n\nProject scaffold generated by `penda new`.\n"

	if err := os.WriteFile(filepath.Join(absPath, "main.go"), []byte(mainFile), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(absPath, "go.mod"), []byte(goModFile), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(absPath, "README.md"), []byte(readmeFile), 0o644); err != nil {
		return err
	}

	_, _ = fmt.Fprintf(stdout, "Project created: %s\n", absPath)
	return nil
}
